image: hashicorp/terraform:full
pipelines:
    default:
        - step:
            script:
                - terraform init
                - terraform validate
                - terraform plan
        - step:
            name: Deploy to dev
            script:
             	- terraform apply -input=false -auto-approve
